"""first migration

Revision ID: 37187aa9257a
Revises: 
Create Date: 2026-03-30 18:07:15.474761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37187aa9257a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_number', sa.String(), nullable=False),
    sa.Column('coach_type', sa.Enum('FIRST_CLASS', 'BUSINESS_CLASS', 'STANDARD_CLASS', name='coachenum'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('id_type', sa.Enum('NIN', 'VOTERSCARED', 'DRIVERSLICENSE', 'PASSPORT', name='idenum'), nullable=False),
    sa.Column('id_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_number'),
    sa.UniqueConstraint('password')
    )
    op.create_table('ticket_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('departure_station', sa.Enum('Abuja', 'LAGOS', 'KANGO', 'PORT_HARCOURT', 'Enugu', name='stationenum'), nullable=False),
    sa.Column('arrival_station', sa.Enum('Abuja', 'LAGOS', 'KANGO', 'PORT_HARCOURT', 'Enugu', name='stationenum'), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='timeenum'), nullable=False),
    sa.Column('booking_status', sa.Enum('BOOKED', 'CANCELLED', 'COMPLETED', name='bookingstatusenum'), nullable=False),
    sa.Column('seat_number', sa.String(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_booking')
    op.drop_table('users')
    op.drop_table('coaches')
    # ### end Alembic commands ###
